pub enum XmlWElement {
    Document,
    Body,
    Paragraph,
    ParagraphProps,
    BorderTop,
    BorderBottom,
    BorderLeft,
    BorderRight,
    BorderBetween,
    Hyperlink,
    Run,
    RunProps,
    Text,
    Bold,
    Italic,
    Strike,
    DStrike,
    Underline,
    Color,
    Size,
    Fonts,
    Highlight,
    VertAlign,
    Spacing,
    KeepNext,
    KeepLines,
    PageBreakBefore,
    WindowControl,
    SuppressLineNumbers,
    ParagraphBorders,
    Shading,
    Tabs,
    Tab,
    NumberingProperties,
    SuppressAutoHyphens,
    WordWrap,
    ToplinePunct,
    AutospaceDe,
    AutospaceDn,
    Bidi,
    SnapToGrid,
    Ind,
    ContextualSpacing,
    MirrorIndents,
    SuppressOverlap,
    Jc,
    TextDirection,
    TextAlignment,
    TextboxTightWrap,
    OutlineLevel,
    Ilvl,
    NumId,
}

impl XmlWElement {
    pub fn as_str(&self) -> &'static str {
        match self {
            XmlWElement::Document => "w:document",
            XmlWElement::Body => "w:body",
            XmlWElement::Paragraph => "w:p",
            XmlWElement::ParagraphProps => "w:pPr",
            XmlWElement::Hyperlink => "w:hyperlink",
            XmlWElement::Run => "w:r",
            XmlWElement::RunProps => "w:rPr",
            XmlWElement::Text => "w:t",
            XmlWElement::Bold => "w:b",
            XmlWElement::Italic => "w:i",
            XmlWElement::Strike => "w:strike",
            XmlWElement::DStrike => "w:dstrike",
            XmlWElement::Underline => "w:u",
            XmlWElement::Color => "w:color",
            XmlWElement::Size => "w:sz",
            XmlWElement::Fonts => "w:rFonts",
            XmlWElement::Highlight => "w:highlight",
            XmlWElement::VertAlign => "w:vertAlign",
            XmlWElement::Spacing => "w:spacing",
            XmlWElement::KeepNext => "w:keepNext",
            XmlWElement::KeepLines => "w:keepLines",
            XmlWElement::PageBreakBefore => "w:pageBreakBefore",
            XmlWElement::WindowControl => "w:windowControl",
            XmlWElement::SuppressLineNumbers => "w:suppressLineNumbers",
            XmlWElement::ParagraphBorders => "w:pBdr",
            XmlWElement::Shading => "w:shd",
            XmlWElement::Tabs => "w:tabs",
            XmlWElement::Tab => "w:tab",
            XmlWElement::NumberingProperties => "w:numPr",
            XmlWElement::SuppressAutoHyphens => "w:suppressAutoHyphens",
            XmlWElement::WordWrap => "w:wordWrap",
            XmlWElement::ToplinePunct => "w:toplinePunct",
            XmlWElement::AutospaceDe => "w:autospaceDe",
            XmlWElement::AutospaceDn => "w:autospaceDn",
            XmlWElement::Bidi => "w:bidi",
            XmlWElement::SnapToGrid => "w:snapToGrid",
            XmlWElement::Ind => "w:ind",
            XmlWElement::ContextualSpacing => "w:contextualSpacing",
            XmlWElement::MirrorIndents => "w:mirrorIndents",
            XmlWElement::SuppressOverlap => "w:suppressOverlap",
            XmlWElement::Jc => "w:jc",
            XmlWElement::TextDirection => "w:textDirection",
            XmlWElement::TextAlignment => "w:textAlignment",
            XmlWElement::TextboxTightWrap => "w:textboxTightWrap",
            XmlWElement::OutlineLevel => "w:outlineLevel",
            XmlWElement::BorderTop => "w:top",
            XmlWElement::BorderBottom => "w:bottom",
            XmlWElement::BorderLeft => "w:left",
            XmlWElement::BorderRight => "w:right",
            XmlWElement::BorderBetween => "w:between",
            XmlWElement::Ilvl => "w:ilvl",
            XmlWElement::NumId => "w:numId",
        }
    }
}
